-- USER SQL
CREATE USER splunk_monitor IDENTIFIED BY welcome1 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS
ALTER USER splunk_monitor QUOTA UNLIMITED ON USERS;

-- ROLES
GRANT "SELECT_CATALOG_ROLE" TO splunk_monitor ;
GRANT "CONNECT" TO splunk_monitor ;
